### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mapmeld** [louy/Javascript-Arabic-Reshaper#2]
Hi,
The LICENSE file is the LGPL, but the NPM package.json says it is GPL
It matters because I was thinking about including this as a dependency in the OpenStreetMap iD editor.  If it's GPL (like Python and Java reshaper libraries) then it can't be included in a non-GPL project.  If it's LGPL, it could be.
Can you clarify? Thanks.

**Comment by louy** [comment]
Hi @mapmeld, the license is GPL3. 
I believe I forgot to update the license file when I rewrote this project and published it to npm. I've updated it now. Let me know if you need anything else.
